In [ ]:
import torch
from torch import nn


In [ ]:
device="cuda" if torch.cuda.is_available() else "cpu"
print(device)

cpu


In [ ]:
!mkdir -p /content/dataset


In [ ]:
from google.colab import files
files.upload()  # Select your kaggle.json file here


Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"ashutosh0410","key":"d4bfc0ea3ae09bb09e1b3f9a9950e9d1"}'}

In [ ]:
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json


In [ ]:
!kaggle datasets download -d thedevastator/lambada-word-prediction-dataset -p /content/dataset


Dataset URL: https://www.kaggle.com/datasets/thedevastator/lambada-word-prediction-dataset
License(s): CC0-1.0
 97% 316M/326M [00:05<00:00, 37.2MB/s]
100% 326M/326M [00:05<00:00, 63.1MB/s]


In [ ]:
!unzip /content/dataset/lambada-word-prediction-dataset.zip -d /content/dataset


Archive:  /content/dataset/lambada-word-prediction-dataset.zip
replace /content/dataset/test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

In [ ]:
!ls /content/dataset


lambada-word-prediction-dataset.zip  test.csv  train.csv  validation.csv


In [ ]:
!wget https://www.gutenberg.org/files/100/100-0.txt -O /content/shakespeare.txt


--2024-11-09 11:13:24--  https://www.gutenberg.org/files/100/100-0.txt
Resolving www.gutenberg.org (www.gutenberg.org)... 152.19.134.47, 2610:28:3090:3000:0:bad:cafe:47
Connecting to www.gutenberg.org (www.gutenberg.org)|152.19.134.47|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5618733 (5.4M) [text/plain]
Saving to: ‘/content/shakespeare.txt’

/content/shakespear 100%[===================>]   5.36M  25.8MB/s    in 0.2s    

2024-11-09 11:13:24 (25.8 MB/s) - ‘/content/shakespeare.txt’ saved [5618733/5618733]



In [ ]:
with open("/content/shakespeare.txt", "r") as f:
    text = f.read()

In [ ]:
print("lenght of the dataset is ", len(text))

lenght of the dataset is  5359439


In [ ]:
chars=sorted(set(text))
vocab_size=len(chars)
print("".join(chars))
print(vocab_size)

	
 !&'()*,-.0123456789:;?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_abcdefghijklmnopqrstuvwxyzÀÆÇÉàâæçèéêë‘’“”…
100


In [ ]:

import re

# Remove numbers
cleaned_data = [re.sub(r'\d+', '', i) for i in text]

# Display the result
print(cleaned_data[:1000])


['*', '*', '*', ' ', 'S', 'T', 'A', 'R', 'T', ' ', 'O', 'F', ' ', 'T', 'H', 'E', ' ', 'P', 'R', 'O', 'J', 'E', 'C', 'T', ' ', 'G', 'U', 'T', 'E', 'N', 'B', 'E', 'R', 'G', ' ', 'E', 'B', 'O', 'O', 'K', ' ', '', '', '', ' ', '*', '*', '*', '\n', 'T', 'h', 'e', ' ', 'C', 'o', 'm', 'p', 'l', 'e', 't', 'e', ' ', 'W', 'o', 'r', 'k', 's', ' ', 'o', 'f', ' ', 'W', 'i', 'l', 'l', 'i', 'a', 'm', ' ', 'S', 'h', 'a', 'k', 'e', 's', 'p', 'e', 'a', 'r', 'e', '\n', '\n', 'b', 'y', ' ', 'W', 'i', 'l', 'l', 'i', 'a', 'm', ' ', 'S', 'h', 'a', 'k', 'e', 's', 'p', 'e', 'a', 'r', 'e', '\n', '\n', '\n', '\n', '\n', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'C', 'o', 'n', 't', 'e', 'n', 't', 's', '\n', '\n', ' ', ' ', ' ', ' ', 'T', 'H', 'E', ' ', 'S', 'O', 'N', 'N', 'E', 'T', 'S', '\n', ' ', ' ', ' ', ' ', 'A', 'L', 'L', '’', 'S', ' ', 'W', 'E', 'L', 'L', ' ', 'T', 'H', 'A', 'T', ' ', 'E', 'N', 'D', 'S', ' ', 'W', 'E', 'L', 'L', '\n', ' ', ' ', ' ', 

In [ ]:
chars=sorted(set(cleaned_data))
vocab_size=len(chars)
print("".join(chars))
print(vocab_size)

	
 !&'()*,-.:;?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_abcdefghijklmnopqrstuvwxyzÀÆÇÉàâæçèéêë‘’“”…
91


In [ ]:
# creating an encoding for the cleaned data
stoi={ch:i for i,ch in enumerate(chars)}
itos={i:ch for i,ch in enumerate(chars)}
encode=lambda s:[stoi[c] for c in s]
decode=lambda l:"".join([itos[i] for i in l])

In [ ]:
print(encode("hello world "))


[52, 49, 56, 56, 59, 3, 67, 59, 62, 56, 48, 3]


In [ ]:
# converting the data to tensor
torch_data=torch.tensor(encode(cleaned_data),dtype=torch.long)


In [ ]:
print(torch_data[:1000])

tensor([ 9,  9,  9,  3, 34, 35, 16, 33, 35,  3, 30, 21,  3, 35, 23, 20,  3, 31,
        33, 30, 25, 20, 18, 35,  3, 22, 36, 35, 20, 29, 17, 20, 33, 22,  3, 20,
        17, 30, 30, 26,  3,  0,  0,  0,  3,  9,  9,  9,  2, 35, 52, 49,  3, 18,
        59, 57, 60, 56, 49, 64, 49,  3, 38, 59, 62, 55, 63,  3, 59, 50,  3, 38,
        53, 56, 56, 53, 45, 57,  3, 34, 52, 45, 55, 49, 63, 60, 49, 45, 62, 49,
         2,  2, 46, 69,  3, 38, 53, 56, 56, 53, 45, 57,  3, 34, 52, 45, 55, 49,
        63, 60, 49, 45, 62, 49,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 18, 59, 58, 64, 49,
        58, 64, 63,  2,  2,  3,  3,  3,  3, 35, 23, 20,  3, 34, 30, 29, 29, 20,
        35, 34,  2,  3,  3,  3,  3, 16, 27, 27, 87, 34,  3, 38, 20, 27, 27,  3,
        35, 23, 16, 35,  3, 20, 29, 19, 34,  3, 38, 20, 27, 27,  2,  3,  3,  3,
         3, 35, 23, 20,  3, 35, 33, 16, 22, 20, 19, 40,  3, 30, 21,  3, 16, 29,
        35, 30, 29, 40,  3, 16, 29, 19, 

In [ ]:
train_data=torch_data[:int(0.9*len(torch_data))]
val_data=torch_data[int(0.9*len(torch_data)):]

In [ ]:
# setting up block size and batch size
block_size=64
batch_size=126
n_embd=384
dropout=0.2
n_head=6
n_layer=6

In [ ]:
torch.manual_seed(1337)
def get_batch(val):
    data=train_data if val=="train" else val_data
    ix=torch.randint(len(data)-block_size,(batch_size,))
    x=torch.stack([data[i: i+block_size] for i in ix])
    y=torch.stack([data[i+1: i+block_size+1] for i in ix])
    return x,y

xb,yb=get_batch("train")
print(xb)
print(yb)

tensor([[49, 49, 48,  ..., 52, 64, 10],
        [62, 53, 45,  ..., 62,  3, 52],
        [35, 52, 49,  ..., 16, 58, 48],
        ...,
        [47, 49, 10,  ..., 43,  2,  2],
        [65, 47, 55,  ...,  3, 45, 58],
        [22, 30, 29,  ..., 65, 63,  3]])
tensor([[49, 48, 63,  ..., 64, 10,  3],
        [53, 45, 58,  ...,  3, 52, 49],
        [52, 49, 53,  ..., 58, 48,  3],
        ...,
        [49, 10,  2,  ...,  2,  2, 27],
        [47, 55, 56,  ..., 45, 58, 48],
        [30, 29, 20,  ..., 63,  3, 59]])


In [ ]:
class MultiheadAttention(nn.Module):
    def __init__(self,num_heads,head_size):
        super().__init__()
        self.proj=nn.Linear(n_embd,n_embd)
        self.heads=nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.dropout=nn.Dropout(dropout)

    def forward(self,x):
         out=torch.cat([h(x) for h in self.heads],dim=-1)
         out=self.dropout(self.proj(out))
         return out


In [ ]:
class FeedForward(nn.Module):
    def __init__(self,n_embd):
        super().__init__()
        self.net=nn.Sequential(
            nn.Linear(n_embd,4*n_embd),
            nn.ReLU(),
            nn.Linear(4*n_embd,n_embd),
            nn.Dropout(dropout)
        )

    def forward(self,x):
      return self.net(x)

In [ ]:
class Block(nn.Module):
    def __init__(self,n_embd,n_head):
      # n_embd: embedding dimension , n_head: the number of heads we would like
        super().__init__()
        head_size=n_embd//n_head
        self.sa=MultiheadAttention(n_head,head_size)
        self.ffd=FeedForward(n_embd)
        self.ln1=nn.LayerNorm(n_embd)
        self.ln2=nn.LayerNorm(n_embd)
    def forward(self,x):
      x=x+self.sa(self.ln1(x))
      x=x+self.ffd(self.ln2(x))
      return x

In [ ]:
class BatchNorm1d(nn.Module):
    def __init__(self,dim,eps=1e-5,momentum=0.1):
        super().__init__()
        self.eps=eps
        self.gamma=nn.Parameter(torch.ones(dim))
        self.beta=nn.Parameter(torch.zeros(dim))
    def __call__self(self,x):
        xmean=x.mean(1,keepdim=True)
        xvar=(x-xmean).pow(2).mean(1,keepdim=True)
        xhat=(x-xmean)/torch.sqrt(xvar+self.eps)
        self.out=self.gamma*xhat+self.beta
        return self.out
    def parameters(self):
        return [self.gamma,self.beta]


In [ ]:
from torch.nn import functional as F
class BigramLanguageModel(nn.Module):
    def __init__(self,vocab_size):
        super().__init__()
        self.token_embedding_table=nn.Embedding(vocab_size,n_embd)
        self.position_embedding_table=nn.Embedding(block_size,n_embd)
        self.blocks=nn.Sequential(*[Block(n_embd,n_head=n_head) for _ in range(n_layer)])
        self.lm_head=nn.Linear(n_embd,vocab_size)
        self.ln_f=nn.LayerNorm(n_embd)


    def forward(self,idx,targets=None):
        B,T=idx.shape
        tok_emb=self.token_embedding_table(idx)#B,T,C
        pos_emb=self.position_embedding_table(torch.arange(T,device=device))#T,C
        x=tok_emb+pos_emb #(B,T,C)
        x=self.blocks(x)
        x=self.ln_f(x)
        logits=self.lm_head(x)#(B,T,vocab_size)

        if targets is None:
            loss=None
            # Return logits only when targets is None
            return logits
        else:
          B,T,C=logits.shape
          logits=logits.view(B*T,C)
          targets=targets.view(B*T)
          loss=F.cross_entropy(logits,targets)
          return logits,loss

    def generate(self,idx,max_new_tokens):
        for _ in range(max_new_tokens):
            # Get logits only as the forward method will return only logits when targets is None
            idx_cond=idx[:, -block_size:]
            logits = self(idx_cond)
            logits=logits[:,-1,:]
            probs=F.softmax(logits,dim=-1)
            idx_next=torch.multinomial(probs,num_samples=1)
            idx=torch.cat((idx,idx_next),dim=1)
        return idx

m=BigramLanguageModel(vocab_size)
logits,loss=m(xb,yb)
print(logits.shape)
print(loss)

torch.Size([8064, 91])
tensor(4.7231, grad_fn=<NllLossBackward0>)


In [ ]:
idx=torch.zeros((1,1),dtype=torch.long)
print(decode(m.generate(idx,max_new_tokens=100)[0].tolist()))

AahxpLJgmâLTR;L:KâdcëHVÀPd:é',“ZjX!gy
u!!U‘CctcKDÀbÇkS œbp;lQ)”ELYQêR…ëLOâ“)-tâëXX lQCML	]qFyc*Ç‘â_


In [ ]:
optimizer=torch.optim.AdamW(m.parameters(),lr=3e-4 )

In [ ]:
batch_size=32
for steps in range(500):
    xb,yb=get_batch("train")
    logits,loss=m(xb,yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
print(loss.item())

2.0953006744384766


In [ ]:
print(decode(m.generate(idx=torch.zeros((1,1),dtype=torch.long),max_new_tokens=1000)[0].tolist()))



CFom nikery??

CRANRAS.
Of how a the sich whas offore will this tom of tir’s’s
IMLO.
MFrant; now to the for flo whej to a sirrch
Ton mangselin, wit pesempp fontrongh, stend tomu, we brame
Tho shall thet mur tecil.

FAST.
Pul o thene thro“Grd will Swrienptmuce and of swed you, gars, un
then hush yort werd thirty that she kisgri of Ot fatir.

BALSSW.
A gro fright comnonemh to uptronice.
Nou the of Lemplice aight sup it cantuiguinit.

LIOOè.

Com, me thad ’t wes, that a my I risem slad pean, and ford frign ouke
Wi nock is _caye.]

MINIUR.
In thee the not tadence of of areniaga_.]

FORIV._

 Got do warte if there couge!

RARD.

Cow Vort hurd care thou to hou wist that wo fair murth to up)
HALL
NUS.

 sisat it.
Awith sunts spernait, tan the ton bueeat hom b-midid
I wis thathe wind sate thare of or am tore,
Weich d the this thou wolspece to hou hims and cÉa atosel.

Ep’s Main.

ALABRICH.
Slower. Balive.

LARIO.
Mive gre whiseal on efidestr, Lon impin to by thanith with mads tra
If you deai

In [ ]:
class Head(nn.Module):
    def __init__(self,head_size):
        super().__init__()
        self.key=nn.Linear(n_embd,head_size,bias=False)
        self.query=nn.Linear(n_embd,head_size,bias=False)
        self.value=nn.Linear(n_embd,head_size,bias=False)
        self.register_buffer('tril',torch.tril(torch.ones(block_size,block_size)))
        self.dropout=nn.Dropout(dropout)

    def forward(self,x):
      B,T,C=x.shape
      k=self.key(x) #(B,T,C)
      q=self.query(x)#(B,T,C)
      # attention scores
      wei=q@k.transpose(-2,-1)*C**-0.5 #(B,T,C)@(B,C,T)->(B,T,T)
      wei=wei.masked_fill(self.tril[:T,:T]==0,float('-inf'))
      wei=F.softmax(wei,dim=-1)
      wei=self.dropout(wei)
      v=self.value(x)
      out=wei@v
      return out


